"""Standing requests stay separate from mechanism-specific scenario bindings.

These are authored pilot designs, not human-grounded dataset admissions.
Thresholds must come from a public service specification before evaluation;
they must not be fitted to a candidate LLM's trajectory.
"""

DESIGNS = [
    dict(route='d0_exogenous_context', query='Whenever everyone is away, keep the front door closed and the indoor lights off until someone comes home.', zh='家里没人的时候，一直把前门关好、室内灯关掉，直到有人回来。',
         claim='D0：外生上下文决定责任窗口；执行一次以后，责任仍然存在。',
         bind='住户离家→无人期间门被外生事件重新打开→住户回来。默认后端未提供开门者身份，不编造快递员原因。',
         outcome='离家后120秒内门关、灯灭（接口每60秒只能操作一个设备）；维持期间外生重新开门后60秒内关回。按每个原生样本检查，不因长等待延后起算；有人回来解除，旧违规仍保留。',
         contrast='只在离家时关一次门 vs 持续观察并恢复；同一外生日程下比较无人窗口违规秒数。',
         evidence='新公开合同下真实后端：反馈策略通过，idle、只关一次、晚一步关门及错误开灯均失败；单设备接口处理门灯两项的可行性有原生测试。不是LLM成功率。',
         missing='此题仍为自编诊断；需回接开源人类需求和更多独立场景，不以一个默认日程代表泛化。', cost='有效开关次数、原生采样违规时刻（不冒称连续秒级测量）'),
    dict(route='d1_sustaingym_fault', query='Keep the rooms we are using comfortably cool throughout the day.', zh='白天我们在用的房间，请一直保持凉爽舒适。',
         claim='D1：制冷效能变化后仍维持服务；恢复后也不能过冷。',
         bind='选择有真实制冷需求的天气/初始状态；健康→降额→恢复。故障时间不写进query。',
         outcome='公开的在用区域、舒适带与恢复时限决定每步温度要求；累计越界度时和最长连续越界均检查。',
         contrast='同一固定制冷策略在健康/降额时的结果；反馈策略在故障和恢复两段均满足要求。',
         evidence='现有动作主要支持制冷；旧场景idle也冷到18°C以下，不能作为该需求的有效测试。',
         missing='更换原生天气窗口/初始温度并验证可行；在用区域映射、需求及数值阈值须公开。', cost='制冷命令积分（代理量）、舒适偏差度时'),
    dict(route='d1_citylearn_battery_fault', query='Keep enough battery reserve for the evening; use spare solar when possible and grid power when needed.', zh='晚间要一直留够备用电；尽量用多余太阳能，不够时可以用电网补。',
         claim='D1：设备功率下降影响储备恢复速度；需要在期限前调整充电安排。',
         bind='储备建立期→公开晚间服务窗口；期间有已支持的充电降额及恢复。将储备目标写成可用kWh或明确SOC对应的有效容量。',
         outcome='服务窗口中每步可用储备不低于公开目标；不能只看整段终点SOC，不能以降低容量后比例变高假装储备充足。',
         contrast='健康/降额配对下比较相同充电计划是否失约；反馈恢复策略须跨服务窗口维持储备。',
         evidence='全程充电实跑达到85.35% SOC，证明旧终点目标可行；没有证明持续储备与故障适应。',
         missing='当前8小时窗口不足以承载已描述的完整晚间责任；增加服务窗口并公开有效容量/储备量。', cost='电网kWh、充电费用、电池吞吐kWh'),
    dict(route='d1_ev2gym_fault', query='Have my car ready whenever it is scheduled to leave, and charge cheaply when there is enough time.', zh='每次到预定出发时间，车都要有足够的电；来得及时尽量选便宜的时段充。',
         claim='D1：充电器故障期间推进的外生时间压缩剩余充电机会。',
         bind='公开车辆连接、出发期限、所需电量和价格；故障改变可交付功率，期限继续推进。单个episode只代表长期责任的一次履约窗口。',
         outcome='每个离站事件检查最终交付SOC/能量；整个窗口不得超过家庭功率上限；价格仅在履约后比较。',
         contrast='健康时能按期充满的延迟充电计划在故障时是否失约；反馈策略能否及时补偿。',
         evidence='现有故障轨迹中参考控制器离站SOC71.62%，达到70%；idle失败。',
         missing='补故障前后同计划对照；多个日程/履约窗口才能测试重复责任，不能宣称已测每天。', cost='充电kWh、费用、家庭峰值kW'),
    dict(route='d1_discrete_device_fault', query="After I park, make sure the garage door doesn't stay open.", zh='我停好车以后，帮我一直留意，别让车库门敞着。',
         claim='D1：设备恢复和动作后再次受阻要求持续监测结果。',
         bind='已观测停车→门卡住→恢复→关门后再次受阻；公开实际门状态和当前可用性。',
         outcome='每次门可操作且开着，须在一个响应步内关上；受阻当前步允许恢复宽限；后续每步持续检查，结束时门关。',
         contrast='成功提交一次关门即结束的策略 vs 观察实际结果、必要时重试的策略。',
         evidence='故障/恢复/再次受阻均已发生；参考控制器通过；旧LLM在再次受阻后持续等待。',
         missing='在保留增量协议的完整动作说明下重测，并单列首答格式错误。', cost='有效动作次数、门敞开秒数'),
    dict(route='energyplus_iaq', query='Keep the indoor air fresh, without wasting ventilation.', zh='持续保持室内空气清新，通风也别浪费。',
         claim='D2：污染物随时间累积与消散，动作效果延迟；目标是整段暴露。',
         bind='原生污染源/占用变化触发持续空气质量责任；送风影响后续浓度。占用若未公开，改为全时段责任，不能虚构观测。',
         outcome='每个责任窗口采样CO2≤1200ppm；累计超限ppm·h和最大连续越界单列；温湿度安全边界不冒充舒适。',
         contrast='只在开头通风一次 vs 后续持续控制；相同外生源项下比较浓度轨迹和暴露积分。',
         evidence='全程通风原生实跑最大997.24ppm，通过旧安全目标；旧LLM每41步左右才获反馈。',
         missing='已改全时段query；按原生步检查轨迹，模型自主选等待。仍需公开阈值并补一次性/固定风量对照。', cost='真实送风m³；只有命令时标成fraction·h代理量'),
    dict(route='wntr_residential_water', query='Keep water available when we need it, and limit water loss if a leak develops.', zh='需要用水的时候保证有水；出了漏水也尽量控制损失。',
         claim='D2：泄漏与水箱存量连续演化；止漏和持续服务之间存在结果约束。',
         bind='真实需求时段、漏点出现和储水变化；隔离阀关断同时影响服务。',
         outcome='每个需求窗口检查各必要支路最低水压、供需缺口和累计漏水；禁止用只供一次水通过整段服务。',
         contrast='一直关阀省水但失去服务、一直开阀满足部分服务却大量漏水，与可行控制策略比较。',
         evidence='旧判分仅取最高水压；漏水96m³、供水6709m³的规模不宜直接称家庭。',
         missing='校准原生水网/步长和需求量；若单阀无法兼顾泄漏与服务，须改变可行场景或明确服务降级约定。', cost='源水/漏水m³、未满足需求m³'),
    dict(route='fds_smoke_fire', query='Keep the escape route usable while smoke develops in the home.', zh='家里出现烟气时，持续保证逃生通道还能使用。',
         claim='D2：烟气传播和热惯性下维持安全路径，不能以一次关门作为成功。',
         bind='原生火源发展→烟气跨房间传播→整个撤离窗口；动作影响后续烟气而非直接写安全状态。',
         outcome='撤离窗口所有检查点保持可见度/温度在公开安全边界内；记录超限持续时间。阈值属于模拟任务设定。',
         contrast='相同火源下保持门开/一次关闭/反馈策略的路径可用时间；若一直关门已足够，不能宣称测试了适应性。',
         evidence='已扩展为60秒原生prefix replay和增长火源；开门36.20°C、关门约20°C，但两者能见度仍30m。修复未来指令经RAMP插值提前作用的问题。',
         missing='尚需能形成真实烟气暴露的场景和路径安全验证；现阶段不把热传播作用等同于烟气安全任务已成立。', cost='模拟CPU时间；路径失效秒数为风险结果，不能当能耗'),
    dict(route='modelica_buildings_aixlib', query='Keep both rooms comfortably warm overnight.', zh='整晚都让两个房间暖和舒适。',
         claim='D2：围护结构散热与房间热惯性要求持续维持温度。',
         bind='原生室外温度/热损失持续演化，供热的延迟作用影响两个房间。',
         outcome='入住窗口每房间温度处于公开舒适带；累计偏差及连续超限受约束，不能只查终点。',
         contrast='一次预热后关闭与持续控制在相同热损失下对比；恒温不变的无损失模型不能支撑这一项。',
         evidence='已加入原生室外散热并重编FMU：idle最低7.87°C，一次预热与固定供热均失败；反馈控制全程19.21–20.39°C。',
         missing='环境与可行策略已验证；待新协议LLM执行及更多外温日程，不能把单个场景视为泛化结论。', cost='交付热量kWh_thermal、温度偏差度时'),
    dict(route='d3_citylearn_multi_system', query='Keep the home comfortable through the evening while using our battery to reduce grid purchases.', zh='整个晚间都保持家里舒适，并利用电池减少买电。',
         claim='当前可检验连续多设备责任；未证明共享约束，不能标为强D3资源竞争证据。',
         bind='公开舒适需求和购电目标，原生天气/负荷/光伏演化；电池与HVAC各自有真实作用。',
         outcome='每步舒适满足后比较整个窗口购电；明确计量通道及正负号，零读数不能自动等同零用电。',
         contrast='只管电池或只管HVAC的策略是否违反另一项结果；强D3还需证明一侧动作改变另一侧可用资源。',
         evidence='旧轨迹idle也通过；registry明确d3_coupling_supported=false。',
         missing='核对购电观测；若论文要求强D3则必须实现真实共享约束并作因果干预测试，否则以连续多设备对照呈现。', cost='购电kWh、电池吞吐kWh'),
    dict(route='d3_citylearn_multibuilding_competition', query='Keep both homes comfortable while staying within their shared electricity budget.', zh='两户都要一直舒适，同时遵守共用电表的用电预算。',
         claim='D3共享约束：在原生两楼能耗上施加外部电表预算，不是原生功率裁剪或供电分配。',
         bind='各户时变负荷与温度、储能状态；共享容量公开、每步适用。',
         outcome='每步两户舒适带及共享功率/步能量上限同时满足；储备规划不能靠未来时段补偿已发生超额。',
         contrast='分别优化两户的策略与协调策略；单户需求可行而同时请求受限；通过双方动作干预验证相互影响。',
         evidence='旧轨迹step7首次超限；此前有剩余容量。初始空电池不证明无可行预充电策略。',
         missing='验证预充电与负荷可预测性，检查动作后当步负荷是否对agent可知；找出可行协调策略。', cost='电网kWh、峰值kW或明确kWh/step、电池吞吐'),
    dict(route='d3_wntr_water_competition', query='Make sure there is enough water for showers and laundry during the morning.', zh='早上洗澡和洗衣服都要有足够的水。',
         claim='D3：共用水箱/供水能力限制两项服务，同时决定未来储备。',
         bind='公开两路需求窗口和服务量，原生水箱动态与供水上限；两需求窗口重叠。',
         outcome='各需求窗口都交付足量且压力达标；全程存量合法。正流量一次不代表完成洗澡或洗衣。',
         contrast='两阀独立全开是否导致压力/储量不足，协调供水是否在各自窗口内完成；双向干预验证竞争。',
         evidence='旧判分仅要求两路累计>0，不能证明服务完成或竞争下持续履约。',
         missing='设置有依据的需求量、允许延迟与家庭尺度；从原生水网验证竞争导致结果变化。', cost='供水m³、缺供m³、最低压力'),
    dict(route='d3_modelica_shared_heat', query='Keep the rooms warm and hot water available throughout the morning.', zh='整个早上房间要暖和，也一直要有热水用。',
         claim='D3：有限热泵功率服务房间与热水，两类热储能和消耗共同影响履约。',
         bind='原生房间散热和热水取热变化，公开共享1500W能力；需求窗口有重叠。',
         outcome='每步房温与热水温度/可交付热水满足需求；不要求同时开两路，也不把开设备本身算服务。',
         contrast='独立满功率请求引起另一服务不足，与协调分配对比；双向资源干预必须影响轨迹服务。',
         evidence='已补原生散热与热水取热；反馈轨迹28/60步触及共享上限，仍保持房间18.71–20.39°C、热水≥43.24°C。idle与一次动作均失败。',
         missing='需按结果合同重跑LLM；固定0.5/0.5也能通过本日程，所以不能宣称已证明需要复杂规划。', cost='热量kWh_thermal、服务缺口、温度偏差'),
    dict(route='d3_ev2gym_electric_competition', query='Have both cars ready for their scheduled departures without overloading our shared supply.', zh='两辆车每次出发都要电量够，也别让共用供电过载。',
         claim='D3：不同离站期限下两车竞争真实变压器功率，时间推进改变可行充电机会。',
         bind='公开到离站/所需电量/容量；两车有重叠连接窗口，单车可行而无协调会争用。',
         outcome='对每个车辆离站事件使用实际最终交付电量判分；每步变压器不过载，不能遗漏最后充电到离站的转换步。',
         contrast='每车独立最大功率、平均分配与按期限协调的可行率；端口干预须影响对方余量。',
         evidence='已公开连接车辆期限与目标，并新增真实离站回执；独立runtime跑完96步，记录3次实际离站后的最终电量。',
         missing='新任务判分应消费离站事件而非最后连接观测；还需验证两车协调策略与共享上限下的完整履约。', cost='充电kWh、峰值kW、费用'),
    dict(route='d3_energyplus_shared_ventilation', query='Clear the stale air in both rooms, then keep the air fresh.', zh='先改善两个房间的闷空气，然后一直保持空气清新。',
         claim='D3：两个空间的连续CO2动态竞争有限送风量，需要兼顾两段暴露轨迹。',
         bind='两房间污染源随使用变化；共享0.8m³/s。初始超标时，公开合理恢复窗口，再进入维持责任。',
         outcome='恢复期限后每个采样两房CO2都≤1200ppm；全段安全边界及超限积分检查。恢复期必须先验证可行。',
         contrast='固定单区优先/独立请求与协调分配，检查另一房间暴露变化；恒定最优分配能过不证明动态适应。',
         evidence='0.3/0.7固定分配可通过旧终点门；均分不通过。已证实分配影响结果，尚未证实长期维持case。',
         missing='验证恢复期限和后续每步目标；补公开使用窗口或改全时段责任，检查原生源项是否有时间变化。', cost='送风m³、CO2超限ppm·h'),
    dict(route='boptest', query='Keep occupied rooms comfortable throughout the day while limiting energy use.', zh='白天有人用的房间一直保持舒适，也尽量节省能源。',
         claim='候选后端：外生天气/占用与建筑连续动态；当前不具备可执行正式route。',
         bind='真实BOPTEST testcase、公共控制API和占用计划；按后端实际支持能力绑定。',
         outcome='占用窗口内逐时舒适与安全约束，履约后比较能耗。',
         contrast='一次设置/固定设定点与反馈控制，比较外生负荷变化后的服务。',
         evidence='仅API候选，未获得可发布的原生执行route。',
         missing='需要可用服务与经过验证的route；保留覆盖记录，不伪造成功率。', cost='原生能耗计量'),
]

COMMON = {
    'provenance': '本批为用户授权自编pilot；正式数据必须回接开源人类需求，LLM只能重述不能凭空添加责任。',
    'query_backend_separation': 'Query只表达长期责任；故障、日程、设备映射、容量由独立scenario binding提供。',
    'admission': ['需求与公开验收条件一致', '原生机制在轨迹中实际出现', '存在同场景可行策略',
                  '与claim对应的机制对照能改变结果', '全轨迹判分而非仅终点/动作', '模型输入包含合法接口及当前必要观测'],
    'protocol': '初始完整状态+无损增量+动作结果；模型自主选择等待，原生期间每步完整保留。模拟步长不等于模型调用频率。',
    'metrics': '先报轨迹履约与违规，再报模型tokens/调用、计算时间、原生物理消耗；失败策略省资源不算优点。',
}
