timescale: 15
simulation_length: 96
year: 2022
month: 1
day: 17
random_day: False
random_hour: False
hour: 5
minute: 0
simulation_days: weekdays
scenario: private
spawn_multiplier: 10
discharge_price_factor: 1
v2g_enabled: False
number_of_charging_stations: 2
number_of_transformers: 1
number_of_ports_per_cs: 1
charging_network_topology: __TOPOLOGY__
simulate_grid: False
network_info:
  vm_pu: 1.0
  s_base: 1000
  load_multiplier: 1
  pv_scale: 80
  bus_info_file: './ev2gym/data/network_data/node_34/Nodes_34.csv'
  branch_info_file: './ev2gym/data/network_data/node_34/Lines_34.csv'
pf_solver: Laurent
power_setpoint_enabled: False
power_setpoint_flexiblity: 70
tr_seed: 23
inflexible_loads:
  include: False
  inflexible_loads_capacity_multiplier_mean: 1
  forecast_mean: 30
  forecast_std: 5
solar_power:
  include: False
  solar_power_capacity_multiplier_mean: 1
  forecast_mean: 20
  forecast_std: 5
demand_response:
  include: False
  events_per_day: 0
  event_capacity_percentage_mean: 35
  event_capacity_percentage_std: 5
  event_length_minutes_min: 60
  event_length_minutes_max: 60
  event_start_hour_mean: 12
  event_start_hour_std: 2
  notification_of_event_minutes: 60
heterogeneous_ev_specs: False
ev_specs_file: ./ev2gym/data/ev_specs_ev_plus_phev.json
transformer:
  max_power: 15
charging_station:
  min_charge_current: 0
  max_charge_current: 32
  min_discharge_current: 0
  max_discharge_current: 0
  voltage: 230
  phases: 3
ev:
  battery_capacity: 50
  max_ac_charge_power: 11
  min_ac_charge_power: 0
  max_dc_charge_power: 50
  max_discharge_power: -11
  min_discharge_power: 0
  ev_phases: 3
  charge_efficiency: 1
  discharge_efficiency: 1
  transition_soc: 1
  min_battery_capacity: 5
  min_time_of_stay: 60
  min_emergency_battery_capacity: 25
  desired_capacity: 1
  transition_soc_multiplier: 5
