from .adapter_registry import AdapterRegistry, DuplicateAdapterError
from .compiler import CompileReport, UnifiedCompiler
from .evaluator import (
    ClauseResult,
    EvaluationResult,
    StateTrajectory,
    evaluate_clause,
    evaluate_trajectory,
    lexicographic_better,
)
from .process_pool import (
    PrimaryBindingConflict,
    ProcessConflictError,
    ProcessPool,
    UnknownProcessError,
)
from .types import (
    BackendCapability,
    BindingRole,
    CapabilityStatus,
    ClauseKind,
    Episode,
    PhysicalProcess,
    PhysicalTopology,
    ProcessAdapter,
    ProcessRequirement,
    ResponsibilityContract,
    ResponsibilityLifecycle,
    TrajectoryClause,
)
from .d2_closed_loop import (
    D2ClosedLoopAdapter,
    D2ClosedLoopBackend,
    D2ProtocolError,
    make_d2_backend,
)
from .agent_interface import (
    AgentActionError,
    AgentClosedLoopBackend,
    AgentInterfaceError,
    AgentReceiptAdapter,
    HarnessD1AgentBackend,
    make_agent_backend,
)
from .llm_conversation import (
    CompactObservationConversation,
    ConversationProtocolError,
    apply_observation_delta,
    build_environment_delta_message,
    build_initial_user_message,
    canonical_assistant_action,
    extend_system_content,
    observation_delta,
    public_action_result_from_receipt,
    prompt_template_sha256,
    validate_canonical_conversation,
)

__all__ = [
    "AdapterRegistry",
    "D2ClosedLoopAdapter",
    "D2ClosedLoopBackend",
    "D2ProtocolError",
    "BackendCapability",
    "BindingRole",
    "CapabilityStatus",
    "ClauseKind",
    "ClauseResult",
    "CompileReport",
    "DuplicateAdapterError",
    "Episode",
    "EvaluationResult",
    "PhysicalProcess",
    "PhysicalTopology",
    "PrimaryBindingConflict",
    "ProcessAdapter",
    "ProcessConflictError",
    "ProcessPool",
    "ProcessRequirement",
    "ResponsibilityContract",
    "ResponsibilityLifecycle",
    "StateTrajectory",
    "TrajectoryClause",
    "UnifiedCompiler",
    "UnknownProcessError",
    "evaluate_clause",
    "evaluate_trajectory",
    "lexicographic_better",
    "make_d2_backend",
    "AgentActionError",
    "AgentClosedLoopBackend",
    "AgentInterfaceError",
    "AgentReceiptAdapter",
    "HarnessD1AgentBackend",
    "make_agent_backend",
    "CompactObservationConversation",
    "ConversationProtocolError",
    "apply_observation_delta",
    "build_environment_delta_message",
    "build_initial_user_message",
    "canonical_assistant_action",
    "extend_system_content",
    "observation_delta",
    "public_action_result_from_receipt",
    "prompt_template_sha256",
    "validate_canonical_conversation",
]
